services:
  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    image: maxim000/ui-service:latest

  text-to-speech:
    build:
      context: ./text-to-speech
      dockerfile: Dockerfile
    image: maxim000/tts-service:latest

  scraping-service:
    build:
      context: ./scraping-service
      dockerfile: Dockerfile
    image: maxim000/scraping-service:latest

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: maxim000/backend-service:latest

  authentication-service:
    build:
      context: ./authentication-service
      dockerfile: Dockerfile
    image: maxim000/auth-service:latest
